title: "Pitchart"
description: "Web developer, with Picardie flavour"
logo: "logo.jpg"

# Your site's domain. E.g: http://yoursite.com
url: ""

parsedown_actived: true

# Comments in posts
comments:
    enabled: false
    disqus_shortname: ""

# Information about author
author:
    name: "Pitchart"

    # Social networks
    twitter: "pitchart"
    github: "https://github.com/pitchart"
    bitbucket:
    facebook:
    linkedin:
    gplus:
    youtube:

# Collections
collections:
  posts:
    output: true

  projects:
    output: true

# RSS feed
feed:
    max_item: 10

# Facebook Open Graph
open_graph:
    locale: "fr_FR"

# Code highlight for <pre> and <code> tags
# Powered by http://highlightjs.org/
code_highlight: true

# Site validation
google_verify:
bing_verify:

# Page menus
top_menu:
    - { name: Accueil, url: "/" }
    - { name: Projets, url: "/projets" }
    - { name: Projets, url: "/projets" }

bottom_menu:
    - { name: "Go to Spresso theme web", url: "https://github.com/yosymfony/Spress-theme-spresso" }
